### ISSUE TITLE
AttributeError: 'OryxQwenConfig' object has no attribute 'mm_spatial_pool_mode'

### ISSUE THREAD

**Issue by daixiangzi** [Oryx-mllm/Oryx#1]
```
CUDA_VISIBLE_DEVICES="7"  accelerate launch \
    --num_processes=1 \
    --main_process_port 12349 \
    -m lmms_eval \
    --model oryx \
    --model_args pretrained="/root/THUdyh/Oryx-7B/,device_map=auto" \
    --tasks mme \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_mme \
    --output_path ./logs/

```

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work. We are working on the inference code for lmms-eval and will update a valid version in a day or two days.

**Comment by daixiangzi** [comment]
> Hi, thanks for your interest in our work. We are working on the inference code for lmms-eval and will update a valid version in a day or two days.

ok

**Comment by dongyh20** [comment]
We have updated the evaluation code and scripts, you can have a try!

Feel free to reopen this issue if you have any question.
