### ISSUE TITLE
Error for Oryx-34B

### ISSUE THREAD

**Issue by RonitPatil** [Oryx-mllm/Oryx#11]
I keep running into this error when I try to use the Oryx-34B model, Oryx-7B works perfectly without any errors. Any idea whats going wrong?
![image](https://github.com/user-attachments/assets/00de6b25-f60f-4ace-8e94-d9e1b6582de4)

**Comment by dongyh20** [comment]
We have updated the evaluation code, check the new codebase and scripts!
