### ISSUE TITLE
Error when training the 7B model.

### ISSUE THREAD

**Issue by yxsysu** [Oryx-mllm/Oryx#12]
Hi, authors. Thanks for your great work.
I try to train the 7B model by sh scripts/train_oryx_7b.sh, but the codes raise a error:

AttributeError: 'OryxQwenConfig' object has no attribute 'attention_bias'

How can I fix this? Thanks for your reply.

**Comment by xumingze0308** [comment]
Hi [yxsysu](https://github.com/yxsysu), can I know how you solve this problem? Thanks!

**Comment by yxsysu** [comment]
Sorry, it's been a while, and I have forgotten some details. Could you check if the version of the transformer library is correct?
pip install transformers==4.39.2

**Comment by zxccade** [comment]
> Hi [yxsysu](https://github.com/yxsysu), can I know how you solve this problem? Thanks!

Hi mingze,

I'm having this problem too. Have you figured this out?

I tried transformers==4.39.2, but it doesn't work either.

**Comment by xumingze0308** [comment]
transformers==4.39.2 works for me.

**Comment by MengHao666** [comment]
I tried transformers==4.39.2, but it doesn't work either.

**Comment by MengHao666** [comment]
> > Hi [yxsysu](https://github.com/yxsysu), can I know how you solve this problem? Thanks!
> 
> Hi mingze,
> 
> I'm having this problem too. Have you figured this out?
> 
> I tried transformers==4.39.2, but it doesn't work either.



> > Hi [yxsysu](https://github.com/yxsysu), can I know how you solve this problem? Thanks!
> 
> Hi mingze,
> 
> I'm having this problem too. Have you figured this out?
> 
> I tried transformers==4.39.2, but it doesn't work either.

have you solved the problem
