### ISSUE TITLE
How to inference Oryx 1.5 32 B Model for long video understanding ? Will a single A100 be enough for testing it out ? 

### ISSUE THREAD

**Issue by PHOENIXFURY007** [Oryx-mllm/Oryx#21]
Can it be inferred just by using  :
 1.[Oryx-ViT](https://huggingface.co/THUdyh/Oryx-ViT)
 2.[Qwen-2.5-32B](https://huggingface.co/Qwen/Qwen2.5-32B-Instruct)
 
 Or do we need the intermediate model ? There was not a detailed readme so I was hoping for more details for testing it out.
 
 Thanks .

**Comment by dongyh20** [comment]
Hi，
To inference Oryx-1.5 32B, you need to download our 32B model from [here](https://huggingface.co/THUdyh/Oryx-1.5-32B) along with the Oryx-ViT. With these two components you can inference our model.

Single A100 will not be able to inference such a large model, as we need to use tensor parallel across multiple GPUs. You may use the scripts [here](https://github.com/Oryx-mllm/Oryx/blob/main/inference_34b.sh) for 32B evaluation with multiple GPUs

**Comment by PHOENIXFURY007** [comment]
How many GPUs are needed for inferencing Oryx-1.5 32B for long video understanding task ?

**Comment by dongyh20** [comment]
In our setting, we use 8 A100 GPUs to conduct tensor parallel.
