### ISSUE TITLE
Oryx-1.5-Image Intermediate Model

### ISSUE THREAD

**Issue by xumingze0308** [Oryx-mllm/Oryx#24]
Hi,

1. Can we ask if you still plan to release the Oryx-1.5-Image intermediate models, 7B and 32B?
2. In your [hugginface data](https://huggingface.co/datasets/THUdyh/Oryx-SFT-Data/tree/main), there are **data.json** and **movie net_data.json**. Which one we should use to reproduce the Oryx-1.5-Image intermediate models?
3. Following the above question, we should use both of them to reproduce the full Oryx-1.5 performance, right? What is the data mixture ratio do you use in the paper?

Thank you!

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work!
1. We have trained an obviously stronger text-image base model and we are planning to release the new model soon. You can use our new model for a better replacement. 
2. Our text-image training data is collected from open-sourced academic datasets (mainly from LLaVA-OneVision, Cauldron, and Cambrian-1), and you can also obtain stronger image data from more recent works. Therefore we do not have a plan to release text-image training data. 
3. You can simply use `data.json` to reproduce most of the results of Oryx-1.5, initializing from image intermediate models. You can mix `movie_net_data.json` for better performance on long video understanding. We mix 10k movie net data with the main data for training Oryx-1.5.
