### ISSUE TITLE
How much GPU memory is needed to fine-tune the 7B model using LoRA?

### ISSUE THREAD

**Issue by Gary-code** [Oryx-mllm/Oryx#3]
How much GPU memory is needed to fine-tune the 7B model using LoRA?

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work! We have not tried the LoRA finetuning before. For reference, we train Oyrx-7B for full fine-tuning with NVIDIA A100 40G GPU, deepspeed zero3, 16k context length, batch size per device=2. Therefore, 40B is sufficient for LoRA fine-tuning, and you can also try on 24GB GPUs with a smaller batch size.
