### ISSUE TITLE
Fine-tuning data template

### ISSUE THREAD

**Issue by Gary-code** [Oryx-mllm/Oryx#4]
Could you provide an example of a JSON template for fine-tuning multiple images?

**Comment by liuzuyan** [comment]
We follow the JSON format in LLaVA when conducting our experiments. The format is as follows:
```
{"image": [path1, path2, path3], 
"conversations": ["from": "human", "value": "<image><image><image>\n text",
"from": "gpt", "value": "response"]},
```
If you use multiple images of different resolutions for input, then the number of the image placeholder (<image>) should be equal to the number of images. If you use video data or single image data, then just use one image placeholder and the code will put all the frames into the sequence. 

Note that we pack the images into patches for our experiments, which is more efficient than loading image files one by one. We will release our packing method and data JSON in a few days.
