### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_loaded'

### ISSUE THREAD

**Issue by daixiangzi** [Oryx-mllm/Oryx#6]
```
CUDA_VISIBLE_DEVICES="7"  accelerate launch \
    --num_processes=1 \
    --main_process_port 12349 \
    -m lmms_eval \
    --model oryx_image \
    --model_args pretrained="/vlm/pretrain_models/THUdyh/Oryx-7B-Image/,device_map=auto" \
    --tasks mme \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_mme \
    --output_path ./logs/

```

**Comment by dongyh20** [comment]
We have fixed the issue in Oryx-7B-Image and Oryx-34B-Image models on the huggingface, please download the newest model to test. You can follow the instructions in README to test our models.

**Comment by daixiangzi** [comment]
> We have fixed the issue in Oryx-7B-Image and Oryx-34B-Image models on the huggingface, please download the newest model to test. You can follow the instructions in README to test our models.

ok
