### ISSUE TITLE
Error when running inference.py

### ISSUE THREAD

**Issue by JoeLeelyf** [Oryx-mllm/Oryx#9]
I follow the instruction to run inference.py using the 34B-model download from huggingface, but got the following error:
![Screenshot 2024-09-26 at 21 16 44](https://github.com/user-attachments/assets/c4829aef-7ba9-41d9-bca9-7ed753f993e9)
It seems that the tokenizer is not properly configured.
And when I run inference.py using the 7B model, I got:
![Screenshot 2024-09-26 at 21 19 49](https://github.com/user-attachments/assets/d814f521-4cfc-4f8a-8c13-768f70cce93b)

**Comment by raoyongming** [comment]
Hi @JoeLeelyf, our models are trained with bf16.  You may use Pytorch >= 2.1 to support bilinear interpolation for bf16 tensors.

**Comment by liuzuyan** [comment]
For `inference.py`, this is a bug caused by the difference between Yi and Qwen2, we are fixing the bug and will update the available file tomorrow.

**Comment by dongyh20** [comment]
We have updated the code supporting the inference of 34B model, you may try it yourself.

**Comment by JoeLeelyf** [comment]
I used the updated code and corrected my PyTorch version to 2.4.1. The 7B model works now but when running the 34B model, I met with the following problem:
![Screenshot 2024-09-27 at 22 08 04](https://github.com/user-attachments/assets/c370c756-44f6-4a48-9fbe-2648b434af4f)

**Comment by dongyh20** [comment]
Sorry for the late reply. New codebase and scripts for eval 34B model are updated.
